// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/0xPolygonHermez/zkevm-node/etherman/types"
)

// TxmanagerMock is an autogenerated mock type for the txManager type
type TxmanagerMock struct {
	mock.Mock
}

// SequenceBatches provides a mock function with given fields: ctx, sequences
func (_m *TxmanagerMock) SequenceBatches(ctx context.Context, sequences []types.Sequence) {
	_m.Called(ctx, sequences)
}

type mockConstructorTestingTNewTxmanagerMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxmanagerMock creates a new instance of TxmanagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxmanagerMock(t mockConstructorTestingTNewTxmanagerMock) *TxmanagerMock {
	mock := &TxmanagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
