---
run:
  timeout: 5m

linters:
  enable:
  - whitespace
  - gosec
  - gci
  - misspell
  - gomnd
  - gofmt
  - goimports
  - revive

linters-settings:
  revive:
    rules:
    - name: exported
      arguments:
      - disableStutteringCheck

issues:
  include:
  - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
  - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
