version: '3'
services:
    hez-core:
        container_name: hez-core
        # restart: always
        image: hezcore
        ports:
            - 8123:8123
        environment:
          - HERMEZCORE_DATABASE_USER=test_user
          - HERMEZCORE_DATABASE_PASSWORD=test_password
          - HERMEZCORE_DATABASE_NAME=test_db
          - HERMEZCORE_DATABASE_HOST=hez-postgres
          - HERMEZCORE_ETHERMAN_PRIVATEKEYPATH=/pk/keystore
        volumes:
          - ./test/test.keystore:/pk/keystore
          - ./cmd/config.toml:/app/config.toml
        command: ["./hezcore", "run", "--network", "local", "--cfg", "/app/config.toml"]

    hez-postgres:
        container_name: hez-postgres
        restart: always
        image: postgres
        ports:
            - 5432:5432
        environment:
            # In order to update this values, you may need to run: docker rm -f -v postgres
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DB=test_db

    hez-explorer:
        container_name: hez-explorer
        restart: always
        image: ulamlabs/blockscout:latest
        ports:
          - 8080:4000
        environment:
          - COIN=ETH
          - ETHEREUM_JSONRPC_VARIANT=geth
          - ETHEREUM_JSONRPC_HTTP_URL=http://hez-core:8123
          - DATABASE_URL=postgres://test_user:test_password@hez-postgres:5432/test_db
          - ECTO_USE_SSL=false

    hez-network:
        container_name: hez-network
        restart: always
        image: hermeznetwork/geth-zkevm-contracts:latest
        ports:
          - 8545:8545