global:
  scrape_interval:     3s # By default, scrape targets every 15 seconds.
  evaluation_interval: 3s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: zkevm-node
    scrape_interval: 3s
    metrics_path: /metrics
    static_configs:
      - targets:
          - zkevm-json-rpc:9091 #inside port of the zkevm-json-rpc
          - zkevm-sequencer:9091 #inside port of the zkevm-sequencer