// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/ethereum/go-ethereum/core/types"
)

// Mock verify always verifies to true
func (_m *PoolMock) VerifyTx(ctx context.Context, tx types.Transaction, ip string) error {
	return nil
}
