// Code generated by mockery v2.39.0. DO NOT EDIT.

package ethtxmanager

import (
	common "github.com/ethereum/go-ethereum/common"
)

// GetZkEvmAddress provides a mock function with given fields:
func (_m *ethermanMock) GetZkEVMAddressAndL1ChainID() (common.Address, uint64, error) {
	return common.Address{}, 0, nil
}

