[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "localhost"
Port = "5432"
EnableLog = true
MaxConns = 10

[Etherman]
URL = "http://localhost:8545"
PrivateKeyPath = "../test/test.keystore"
PrivateKeyPassword = "testonly"

[RPC]
Host = "0.0.0.0"
Port = 8123
MaxRequestsPerIPAndSecond = 10

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[Sequencer]
AllowNonRegistered = "false"
IntervalToProposeBatch = "15s"
SyncedBlockDif = 1
InitBatchProcessorIfDiffType = "synced"
    [Sequencer.Strategy]
        [Sequencer.Strategy.TxSelector]
            Type = "acceptall"
            TxSorterType = "bycostandnonce"
        [Sequencer.Strategy.TxProfitabilityChecker]
            Type = "acceptall"
            MinReward = "1.1"
    [Sequencer.PriceGetter]
        Type = "default"
        DefaultPrice = "2000"

[Aggregator]
IntervalToConsolidateState = "10s"
IntervalFrequencyToGetProofGenerationStateInSeconds = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"

[GasPriceEstimator]
Type = "default"
DefaultGasPriceWei = 1000000000

[Prover]
ProverURI = "localhost:50051"

[MTServer]
Host = "0.0.0.0"
Port = 50060
StoreBackend = "PostgreSQL"

[MTClient]
URI = "127.0.0.1:50060"
