// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	"github.com/0xPolygonHermez/zkevm-node/dataavailability/datacommittee"
)

func (_m *EthermanFullInterface) GetCurrentDataCommittee() (*datacommittee.DataCommittee, error) {
	//TODO implement me
	panic("implement me")
}
