// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	etherman "github.com/0xPolygonHermez/zkevm-node/etherman"
)

func (_m *EthermanFullInterface) GetCurrentDataCommittee() (*etherman.DataCommittee, error) {
	//TODO implement me
	panic("implement me")
}