// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	context "context"
	"github.com/jackc/pgx/v4"
)

func (_m *StateFullInterface) GetBatchL2DataByNumber(ctx context.Context, batchNumber uint64, dbTx pgx.Tx) ([]byte, error){
	return nil, nil
}
