// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import mock "github.com/stretchr/testify/mock"

// SynchronizerCleanTrustedState is an autogenerated mock type for the SynchronizerCleanTrustedState type
type SynchronizerCleanTrustedState struct {
	mock.Mock
}

type SynchronizerCleanTrustedState_Expecter struct {
	mock *mock.Mock
}

func (_m *SynchronizerCleanTrustedState) EXPECT() *SynchronizerCleanTrustedState_Expecter {
	return &SynchronizerCleanTrustedState_Expecter{mock: &_m.Mock}
}

// CleanTrustedState provides a mock function with given fields:
func (_m *SynchronizerCleanTrustedState) CleanTrustedState() {
	_m.Called()
}

// SynchronizerCleanTrustedState_CleanTrustedState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanTrustedState'
type SynchronizerCleanTrustedState_CleanTrustedState_Call struct {
	*mock.Call
}

// CleanTrustedState is a helper method to define mock.On call
func (_e *SynchronizerCleanTrustedState_Expecter) CleanTrustedState() *SynchronizerCleanTrustedState_CleanTrustedState_Call {
	return &SynchronizerCleanTrustedState_CleanTrustedState_Call{Call: _e.mock.On("CleanTrustedState")}
}

func (_c *SynchronizerCleanTrustedState_CleanTrustedState_Call) Run(run func()) *SynchronizerCleanTrustedState_CleanTrustedState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SynchronizerCleanTrustedState_CleanTrustedState_Call) Return() *SynchronizerCleanTrustedState_CleanTrustedState_Call {
	_c.Call.Return()
	return _c
}

func (_c *SynchronizerCleanTrustedState_CleanTrustedState_Call) RunAndReturn(run func()) *SynchronizerCleanTrustedState_CleanTrustedState_Call {
	_c.Call.Return(run)
	return _c
}

// NewSynchronizerCleanTrustedState creates a new instance of SynchronizerCleanTrustedState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSynchronizerCleanTrustedState(t interface {
	mock.TestingT
	Cleanup(func())
}) *SynchronizerCleanTrustedState {
	mock := &SynchronizerCleanTrustedState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
