[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "localhost"
Port = "5432"

[Etherman]
URL = "http://hez-network:8545"
PrivateKeyPath = "./test/test.keystore"
PrivateKeyPassword = "testonly"

[RPC]
Host = "0.0.0.0"
Port = 8123

[Sequencer]
IntervalToProposeBatch = "15s"
SyncedBlockDif = 1

[Aggregator]
IntervalToConsolidateState = "3s"

[Prover]
ProverURI = "0.0.0.0:50051"
