// Code generated by mockery. DO NOT EDIT.

package mock_elderberry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"

	state "github.com/0xPolygonHermez/zkevm-node/state"
)

// StateL1SequenceBatchesElderberry is an autogenerated mock type for the StateL1SequenceBatchesElderberry type
type StateL1SequenceBatchesElderberry struct {
	mock.Mock
}

type StateL1SequenceBatchesElderberry_Expecter struct {
	mock *mock.Mock
}

func (_m *StateL1SequenceBatchesElderberry) EXPECT() *StateL1SequenceBatchesElderberry_Expecter {
	return &StateL1SequenceBatchesElderberry_Expecter{mock: &_m.Mock}
}

// GetLastL2BlockByBatchNumber provides a mock function with given fields: ctx, batchNumber, dbTx
func (_m *StateL1SequenceBatchesElderberry) GetLastL2BlockByBatchNumber(ctx context.Context, batchNumber uint64, dbTx pgx.Tx) (*state.L2Block, error) {
	ret := _m.Called(ctx, batchNumber, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastL2BlockByBatchNumber")
	}

	var r0 *state.L2Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, pgx.Tx) (*state.L2Block, error)); ok {
		return rf(ctx, batchNumber, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, pgx.Tx) *state.L2Block); ok {
		r0 = rf(ctx, batchNumber, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.L2Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, pgx.Tx) error); ok {
		r1 = rf(ctx, batchNumber, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastL2BlockByBatchNumber'
type StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call struct {
	*mock.Call
}

// GetLastL2BlockByBatchNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - batchNumber uint64
//   - dbTx pgx.Tx
func (_e *StateL1SequenceBatchesElderberry_Expecter) GetLastL2BlockByBatchNumber(ctx interface{}, batchNumber interface{}, dbTx interface{}) *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call {
	return &StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call{Call: _e.mock.On("GetLastL2BlockByBatchNumber", ctx, batchNumber, dbTx)}
}

func (_c *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call) Run(run func(ctx context.Context, batchNumber uint64, dbTx pgx.Tx)) *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call) Return(_a0 *state.L2Block, _a1 error) *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call) RunAndReturn(run func(context.Context, uint64, pgx.Tx) (*state.L2Block, error)) *StateL1SequenceBatchesElderberry_GetLastL2BlockByBatchNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastVirtualBatchNum provides a mock function with given fields: ctx, dbTx
func (_m *StateL1SequenceBatchesElderberry) GetLastVirtualBatchNum(ctx context.Context, dbTx pgx.Tx) (uint64, error) {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastVirtualBatchNum")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) (uint64, error)); ok {
		return rf(ctx, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) uint64); ok {
		r0 = rf(ctx, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx) error); ok {
		r1 = rf(ctx, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastVirtualBatchNum'
type StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call struct {
	*mock.Call
}

// GetLastVirtualBatchNum is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx pgx.Tx
func (_e *StateL1SequenceBatchesElderberry_Expecter) GetLastVirtualBatchNum(ctx interface{}, dbTx interface{}) *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call {
	return &StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call{Call: _e.mock.On("GetLastVirtualBatchNum", ctx, dbTx)}
}

func (_c *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call) Run(run func(ctx context.Context, dbTx pgx.Tx)) *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx))
	})
	return _c
}

func (_c *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call) Return(_a0 uint64, _a1 error) *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call) RunAndReturn(run func(context.Context, pgx.Tx) (uint64, error)) *StateL1SequenceBatchesElderberry_GetLastVirtualBatchNum_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateL1SequenceBatchesElderberry creates a new instance of StateL1SequenceBatchesElderberry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateL1SequenceBatchesElderberry(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateL1SequenceBatchesElderberry {
	mock := &StateL1SequenceBatchesElderberry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
