// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/0xPolygonHermez/zkevm-node/etherman/types"
	mock "github.com/stretchr/testify/mock"
)

// EthTxManager is an autogenerated mock type for the ethTxManager type
type EthTxManager struct {
	mock.Mock
}

// VerifyBatches provides a mock function with given fields: ctx, lastVerifiedBatch, batchNum, inputs
func (_m *EthTxManager) VerifyBatches(ctx context.Context, lastVerifiedBatch uint64, batchNum uint64, inputs *types.FinalProofInputs) error {
	ret := _m.Called(ctx, lastVerifiedBatch, batchNum, inputs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, *types.FinalProofInputs) error); ok {
		r0 = rf(ctx, lastVerifiedBatch, batchNum, inputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEthTxManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewEthTxManager creates a new instance of EthTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEthTxManager(t mockConstructorTestingTNewEthTxManager) *EthTxManager {
	mock := &EthTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
