// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	pb "github.com/0xPolygonHermez/zkevm-node/proverclient/pb"
	mock "github.com/stretchr/testify/mock"
)

// EthTxManager is an autogenerated mock type for the ethTxManager type
type EthTxManager struct {
	mock.Mock
}

// VerifyBatch provides a mock function with given fields: batchNum, proof
func (_m *EthTxManager) VerifyBatch(batchNum uint64, proof *pb.GetProofResponse) error {
	ret := _m.Called(batchNum, proof)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, *pb.GetProofResponse) error); ok {
		r0 = rf(batchNum, proof)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEthTxManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewEthTxManager creates a new instance of EthTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEthTxManager(t mockConstructorTestingTNewEthTxManager) *EthTxManager {
	mock := &EthTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
