name: build and upload image

on:
  pull_request:
    types:
      - labeled
      - closed
    branches:
      - develop  # Adjust this to the appropriate branch name

jobs:
  build_and_upload:
    if: |
      github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')
    runs-on: ubuntu-latest  # Use the appropriate runner
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zkevm-node:$(date +%s)
