name: CI Build

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
           hermeznetwork/zkevm-node:develop



