name: CI Build

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')
    runs-on: ubuntu-latest

steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t docker:zkevm-node .
          docker push dido21/docker:zkevm-node



