on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hermeznetwork/hermez-node-zkevm:latest
            hermeznetwork/hermez-core:1.5-itestnet

      - name: Build and push prover mock
        id: docker_build_prover_mock
        uses: docker/build-push-action@v2
        with:
          context: ./proverservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hermeznetwork/hez-mock-prover:latest
            hermeznetwork/hez-mock-prover:1.5-itestnet
