on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hermeznetwork/zkevm-node:latest

      - name: Check changes in zkevmprovermock
        id: zkevmprovermock_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            zkevmprovermock:
              - 'tools/zkevmprovermock/**'

      - name: Build and push zkevmprovermock
        if: steps.zkevmprovermock_changes.outputs.zkevmprovermock == 'true'
        id: docker_build_zkevmprovermock
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tools/zkevmprovermock/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hermeznetwork/zkprover-mock:latest
