name: Test
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull L1 network docker image
      run: docker image pull hermeznetwork/hermez-node-zkevm:latest
    - name: Test
      run: make test-full
